### PR TITLE
Click on config path comment copy to clipcoard

### PR DESCRIPTION
**Pull request by mehdichaouch**
Hello @piotr-rusin,

Just a little improvement: 
image

Best Regards,

### CODE REVIEW

**Comment by piorus** [comment]
thank you @mehdichaouch

**Review by danstaver — COMMENTED** [review]
I like the copy feature. The alert? Not so much. 
You have to confirm the alert in order to be able to do anything on the admin panel. I think something less intrusive would be a lot better.

**Comment by mehdichaouch** [comment]
@danstaver maybe using browser notification?

**Comment by piorus** [comment]
maybe a transient fade-out animation of `copied` text? I think that jQuery is available in the admin context to handle it properly

**Comment by piorus** [comment]
@mehdichaouch @danstaver I've added fade-in / fade-out instead of alert, here: https://github.com/pragmatic-modules/magento2-module-system-configuration-toolkit/commit/f686c475211652afff33977ada62cb095ea7b46a

you can now use the newest version (1.1.3) which does support that.

**Comment by danstaver** [comment]
thank you, works like a charm

**Pull request merged**
